package com.daniyal.videograb;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import java.net.URI;
import java.util.*;

public class MainActivity extends Activity {
    private WebView webView; private EditText address; private ProgressBar progress; private Button mediaButton; private TextView pageTitle;
    private final Set<MediaCandidate> candidates=new LinkedHashSet<>();

    @SuppressLint({"SetJavaScriptEnabled","AddJavascriptInterface"})
    @Override protected void onCreate(Bundle b){super.onCreate(b);build();askNotificationPermission();WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);s.setUseWideViewPort(true);s.setLoadWithOverviewMode(true);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(webView,true);webView.addJavascriptInterface(new JsBridge(),"VideoGrabBridge");
        webView.setWebChromeClient(new WebChromeClient(){@Override public void onProgressChanged(WebView v,int p){progress.setProgress(p);progress.setVisibility(p>=100?View.GONE:View.VISIBLE);}@Override public void onReceivedTitle(WebView v,String t){if(t!=null&&!t.trim().isEmpty())pageTitle.setText(t);}});
        webView.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("http".equals(u.getScheme())||"https".equals(u.getScheme()))return false;try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception ignored){}return true;}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){detect(r.getUrl().toString());return super.shouldInterceptRequest(v,r);}@Override public void onLoadResource(WebView v,String u){detect(u);}@Override public void onPageFinished(WebView v,String u){address.setText(u);inject();}});
        handle(getIntent());if(webView.getUrl()==null)load("https://www.google.com");}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handle(i);}

    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,247,250));LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(14),dp(10),dp(14),dp(8));head.setBackgroundColor(Color.rgb(20,24,32));TextView brand=new TextView(this);brand.setText("VideoGrab");brand.setTextColor(Color.WHITE);brand.setTextSize(21);brand.setTypeface(Typeface.DEFAULT,Typeface.BOLD);head.addView(brand);pageTitle=new TextView(this);pageTitle.setText("Advanced browser downloader");pageTitle.setTextColor(Color.rgb(178,187,202));pageTitle.setTextSize(12);pageTitle.setSingleLine(true);head.addView(pageTitle);root.addView(head);
        LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER_VERTICAL);nav.setPadding(dp(6),dp(6),dp(6),dp(6));nav.setBackgroundColor(Color.WHITE);Button back=nav("‹"),forward=nav("›"),reload=nav("↻"),go=nav("Go");address=new EditText(this);address.setSingleLine(true);address.setHint("Search or enter website");address.setTextSize(14);address.setBackgroundColor(Color.rgb(238,241,245));address.setPadding(dp(12),0,dp(12),0);address.setLayoutParams(new LinearLayout.LayoutParams(0,dp(46),1));nav.addView(back);nav.addView(forward);nav.addView(reload);nav.addView(address);nav.addView(go);root.addView(nav);
        progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);root.addView(progress,new LinearLayout.LayoutParams(-1,dp(3)));webView=new WebView(this);webView.setBackgroundColor(Color.WHITE);root.addView(webView,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bottom=new LinearLayout(this);bottom.setPadding(dp(8),dp(6),dp(8),dp(8));bottom.setBackgroundColor(Color.WHITE);mediaButton=action("Detected 0");Button dl=action("Queue & Library");bottom.addView(mediaButton,new LinearLayout.LayoutParams(0,dp(55),1));bottom.addView(dl,new LinearLayout.LayoutParams(0,dp(55),1));root.addView(bottom);setContentView(root);
        back.setOnClickListener(v->{if(webView.canGoBack())webView.goBack();});forward.setOnClickListener(v->{if(webView.canGoForward())webView.goForward();});reload.setOnClickListener(v->webView.reload());go.setOnClickListener(v->load(address.getText().toString()));address.setOnEditorActionListener((v,a,e)->{load(address.getText().toString());return true;});mediaButton.setOnClickListener(v->showMedia());dl.setOnClickListener(v->startActivity(new Intent(this,DownloadsActivity.class)));}
    private Button nav(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(8),0,dp(8),0);b.setLayoutParams(new LinearLayout.LayoutParams(-2,dp(46)));return b;}
    private Button action(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}

    private void handle(Intent i){if(i==null)return;String u=null;if(Intent.ACTION_SEND.equals(i.getAction())){CharSequence x=i.getCharSequenceExtra(Intent.EXTRA_TEXT);if(x!=null)for(String t:x.toString().split("\\s+"))if(t.startsWith("http://")||t.startsWith("https://")){u=t;break;}}else if(Intent.ACTION_VIEW.equals(i.getAction())&&i.getData()!=null)u=i.getData().toString();if(u!=null)load(u);}
    private void load(String raw){String u=raw==null?"":raw.trim();if(u.isEmpty())return;if(!u.startsWith("http://")&&!u.startsWith("https://")){if(u.contains(" ")||!u.contains("."))u="https://www.google.com/search?q="+Uri.encode(u);else u="https://"+u;}synchronized(candidates){candidates.clear();}updateCount();address.setText(u);webView.loadUrl(u);}
    private void detect(String u){add(MediaCandidate.fromUrl(u));}
    private void add(MediaCandidate c){if(c==null)return;boolean changed=false;synchronized(candidates){MediaCandidate old=null;for(MediaCandidate x:candidates)if(x.canonicalKey().equals(c.canonicalKey())){old=x;break;}if(old!=null){old.mergeFrom(c);changed=true;}else{candidates.add(c);changed=true;}}if(changed)runOnUiThread(this::updateCount);}
    private void media(String u,int w,int h,double duration,boolean playing){if(u==null||(!u.startsWith("http://")&&!u.startsWith("https://")))return;MediaCandidate c=MediaCandidate.fromUrl(u);if(c==null)c=new MediaCandidate(u,MediaCandidate.Kind.DIRECT);c.fromMediaElement=true;c.width=w;c.height=h;c.duration=duration;c.playing=playing;add(c);}
    private void updateCount(){int n; synchronized(candidates){n=candidates.size();}mediaButton.setText("Detected "+n);}
    private void inject(){String js="(function(){if(window.__vg)return;window.__vg=1;function bg(u){try{if(u&&/^https?:/i.test(u))VideoGrabBridge.found(u);}catch(e){}}function med(x,u){try{if(!u||!/^https?:/i.test(u))return;var w=x.videoWidth||x.clientWidth||0,h=x.videoHeight||x.clientHeight||0,d=isFinite(x.duration)?x.duration:0,p=!x.paused&&!x.ended&&x.readyState>2;VideoGrabBridge.mediaInfo(u,w,h,d,p);}catch(e){}}function scan(){document.querySelectorAll('video,audio').forEach(function(x){med(x,x.currentSrc);med(x,x.src);x.querySelectorAll('source').forEach(function(s){med(x,s.src);});});try{performance.getEntriesByType('resource').forEach(function(e){bg(e.name);});}catch(e){}}scan();setInterval(scan,1200);var f=window.fetch;if(f)window.fetch=function(){try{bg(arguments[0]&&arguments[0].url?arguments[0].url:arguments[0]);}catch(e){}return f.apply(this,arguments);};var o=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(m,u){bg(u);return o.apply(this,arguments);};})();";webView.evaluateJavascript(js,null);}

    private String pageHost(){try{return new URI(webView.getUrl()).getHost();}catch(Exception e){return null;}}
    private List<MediaCandidate> ranked(){List<MediaCandidate> list; synchronized(candidates){list=new ArrayList<>(candidates);}String host=pageHost();list.sort((a,b)->Integer.compare(b.score(host),a.score(host)));long now=System.currentTimeMillis();List<MediaCandidate> filtered=new ArrayList<>();for(MediaCandidate c:list){int sc=c.score(host);boolean stale=now-c.lastSeen>120000;boolean tiny=(c.width>0&&c.height>0&&(long)c.width*c.height<=320L*180L);boolean veryShort=c.duration>0&&c.duration<10;if(stale&&!c.fromMediaElement)continue;if((tiny||veryShort)&&sc<0)continue;filtered.add(c);if(filtered.size()>=12)break;}return filtered;}

    private void showMedia(){List<MediaCandidate> list=ranked();if(list.isEmpty()){String u=webView.getUrl()==null?"":webView.getUrl().toLowerCase();String msg=(u.contains("youtube.com")||u.contains("youtu.be"))?"YouTube does not expose a normal downloadable stream to VideoGrab. This app does not bypass YouTube signed-stream, DRM, or access controls.":"Play the main video for a few seconds, then tap Detected again. VideoGrab now prioritizes the active/larger player and hides many tiny ad clips.";new AlertDialog.Builder(this).setTitle("No likely video found").setMessage(msg).setPositiveButton("OK",null).show();return;}String host=pageHost();String[] a=new String[list.size()];for(int i=0;i<a.length;i++)a[i]=list.get(i).displayName(host,i==0&&list.get(i).score(host)>300);new AlertDialog.Builder(this).setTitle("Detected media • best match first").setItems(a,(d,w)->inspect(list.get(w))).setNegativeButton("Close",null).show();}

    private void inspect(MediaCandidate c){String ua=webView.getSettings().getUserAgentString(),cookie=CookieManager.getInstance().getCookie(c.url),ref=webView.getUrl();if(c.kind==MediaCandidate.Kind.DIRECT){chooseOutput(c.url,DownloadTask.KIND_DIRECT,"Original",ua,cookie,ref);return;}if(c.kind==MediaCandidate.Kind.DASH){inspectDash(c.url,ua,cookie,ref);return;}ProgressDialog pd=ProgressDialog.show(this,"Checking HLS","Validating stream and finding qualities…",true,false);new Thread(()->{try{List<HlsInspector.Option> o=HlsInspector.inspect(c.url,cookie,ua,ref);runOnUiThread(()->{pd.dismiss();String[] x=new String[o.size()];for(int i=0;i<x.length;i++)x[i]=o.get(i).label;new AlertDialog.Builder(this).setTitle("Choose quality").setItems(x,(d,w)->chooseOutput(o.get(w).url,DownloadTask.KIND_HLS,o.get(w).label,ua,cookie,ref)).show();});}catch(Exception e){runOnUiThread(()->{pd.dismiss();String msg=e.getMessage()==null?"HLS stream is no longer available":e.getMessage();if(msg.contains("HTTP 404"))msg="This HLS link expired or was replaced by the website (HTTP 404). Play the video again for a few seconds, then tap Detected — VideoGrab will use the newest stream URL.";new AlertDialog.Builder(this).setTitle("HLS stream unavailable").setMessage(msg).setPositiveButton("Rescan page",(d,w)->{injectFresh();Toast.makeText(this,"Play the video, then tap Detected again",Toast.LENGTH_LONG).show();}).setNegativeButton("Close",null).show();});}},"hls-inspect").start();}
    private void injectFresh(){webView.evaluateJavascript("try{window.__vg=0;}catch(e){}",v->inject());}

    private void inspectDash(String url,String ua,String cookie,String ref){ProgressDialog pd=ProgressDialog.show(this,"Analyzing DASH","Finding video and audio qualities…",true,false);new Thread(()->{try{List<DashInspector.Option> opts=DashInspector.inspect(url,cookie,ua,ref);runOnUiThread(()->{pd.dismiss();String[] labels=new String[opts.size()];for(int i=0;i<labels.length;i++)labels[i]=opts.get(i).label;new AlertDialog.Builder(this).setTitle("Choose DASH quality").setItems(labels,(d,w)->chooseDashOutput(url,opts.get(w),ua,cookie,ref)).setNegativeButton("Cancel",null).show();});}catch(Exception e){runOnUiThread(()->{pd.dismiss();new AlertDialog.Builder(this).setTitle("DASH not supported").setMessage(e.getMessage()==null?"Could not inspect this DASH manifest":e.getMessage()).setPositiveButton("OK",null).show();});}},"dash-inspect").start();}
    private void chooseDashOutput(String url,DashInspector.Option o,String ua,String cookie,String ref){String[] modes={"Video • "+o.label,"MP3 • 128 kbps","MP3 • 192 kbps","MP3 • 320 kbps"};new AlertDialog.Builder(this).setTitle("Download as").setItems(modes,(d,w)->{DownloadTask t=new DownloadTask();t.url=url;t.kind=DownloadTask.KIND_DASH;t.quality=o.label;t.userAgent=ua==null?"":ua;t.cookie=cookie==null?"":cookie;t.referer=ref==null?"":ref;t.name=title(url);t.dashVideoStream=o.videoStream;t.dashAudioStream=o.audioStream;if(w>0){t.mode=DownloadTask.MODE_MP3;t.mp3Bitrate=w==1?128:w==2?192:320;if(o.audioStream<0){Toast.makeText(this,"No audio track is available for MP3",Toast.LENGTH_LONG).show();return;}}DownloadQueueService.enqueue(this,t);Toast.makeText(this,"DASH added to download queue",Toast.LENGTH_SHORT).show();startActivity(new Intent(this,DownloadsActivity.class));}).setNegativeButton("Cancel",null).show();}
    private void chooseOutput(String url,String kind,String quality,String ua,String cookie,String ref){String[] modes={"Video • "+quality,"MP3 • 128 kbps","MP3 • 192 kbps","MP3 • 320 kbps"};new AlertDialog.Builder(this).setTitle("Download as").setItems(modes,(d,w)->{DownloadTask t=new DownloadTask();t.url=url;t.kind=kind;t.quality=quality;t.userAgent=ua==null?"":ua;t.cookie=cookie==null?"":cookie;t.referer=ref==null?"":ref;t.name=title(url);if(w>0){t.mode=DownloadTask.MODE_MP3;t.mp3Bitrate=w==1?128:w==2?192:320;}DownloadQueueService.enqueue(this,t);Toast.makeText(this,"Added to download queue",Toast.LENGTH_SHORT).show();startActivity(new Intent(this,DownloadsActivity.class));}).setNegativeButton("Cancel",null).show();}
    private String title(String url){String t=pageTitle.getText().toString().trim();if(t.isEmpty()||t.equals("Advanced browser downloader"))t=URLUtil.guessFileName(url,null,null);t=MediaPublisher.stripExtension(t);if(t.length()>80)t=t.substring(0,80);return MediaPublisher.sanitize(t);}
    private void askNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},50);}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    @Override public void onBackPressed(){if(webView.canGoBack())webView.goBack();else super.onBackPressed();}
    public class JsBridge{@JavascriptInterface public void found(String u){detect(u);}@JavascriptInterface public void mediaInfo(String u,int w,int h,double d,boolean p){MainActivity.this.media(u,w,h,d,p);}}
}
